### ISSUE TITLE
Why not unify these two leaderboards into one?

### ISSUE THREAD

**Issue by zhimin-z** [CLUEbenchmark/SuperCLUE-Code3#1]
![image](https://github.com/CLUEbenchmark/SuperCLUE-Code3/assets/8592144/fc24b66a-0802-439d-8a2f-4d64572c0d5a)
It seems a bit redundant to show them separately XD

**Comment by brightmart** [comment]
it could be a good idea. but it is not easy to show all numbers in a small device. the first table is for the total results, the second table shows the results of questions for different levels.
